import type { CharacterClass, SkillCard } from '../../types'

type SkillTemplate = Omit<SkillCard, 'lastUsedAt'>

// Level gates: 1, 5, 10, 15, 20, 30, 40, 55, 70, 99
// Lv99 = ultimate reward skill (ultra-powerful, very long CD)
export const SKILL_MASTER: Record<CharacterClass, Array<{ level: number; skill: SkillTemplate }>> = {
  warrior: [
    { level:  1, skill: { id: 'slash',            name: '斬撃',             type: 'attack',  description: '敵1体に1.5倍の物理ダメージ',                      cooldownMs:  3000, mpCost:  5, autoCondition: 'always' } },
    { level:  5, skill: { id: 'shield_bash',       name: 'シールドバッシュ', type: 'debuff',  description: '敵1体に0.8倍ダメージ＋硬直付与',                  cooldownMs:  8000, mpCost: 10, autoCondition: 'always' } },
    { level: 10, skill: { id: 'war_cry',           name: '鼓舞',             type: 'buff',    description: '自身のATK↑（最大3段）',                           cooldownMs:  8000, mpCost:  8, autoCondition: 'combat_start', buffEffects: ['atk_up'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'fortress',          name: '堅守',             type: 'buff',    description: '自身のDEF↑（最大3段）',                           cooldownMs:  8000, mpCost:  8, autoCondition: 'hp_below_50',  buffEffects: ['def_up'], buffTarget: 'self' } },
    { level: 20, skill: { id: 'whirlwind',         name: '旋風斬',           type: 'attack',  description: '敵全体に1.2倍の物理ダメージ',                      cooldownMs: 12000, mpCost: 18, autoCondition: 'always' } },
    { level: 30, skill: { id: 'heavy_strike',      name: '剛撃',             type: 'attack', description: '敵1体に2.5倍の強力な一撃',                         cooldownMs: 20000, mpCost: 25, autoCondition: 'always' } },
    { level: 40, skill: { id: 'iron_defense',      name: '鉄壁防衛',         type: 'buff',    description: 'パーティ全体のDEF↑',                              cooldownMs: 20000, mpCost: 25, autoCondition: 'combat_start', buffEffects: ['def_up'], buffTarget: 'party' } },
    { level: 55, skill: { id: 'demon_power',       name: '鬼神の力',         type: 'buff',    description: '自身のATK↑↑＋結界',                              cooldownMs: 25000, mpCost: 30, autoCondition: 'hp_below_50',  buffEffects: ['atk_up', 'barrier'], buffTarget: 'self' } },
    { level: 70, skill: { id: 'sword_saint',       name: '剣聖',             type: 'buff',    description: '自身のATK↑＋集中＋速↑',                           cooldownMs: 30000, mpCost: 35, autoCondition: 'combat_start', buffEffects: ['atk_up', 'focus', 'spd_up'], buffTarget: 'self' } },
    { level: 99, skill: { id: 'all_in_strike',      name: '捨て身の一撃',     type: 'attack', description: '【奥義】自身のHPを1にして失った命を力に変換、敵1体に10倍の渾身斬（HP25%以下で発動）', cooldownMs: 90000, mpCost: 40, autoCondition: 'hp_below_25' } },
  ],
  mage: [
    { level:  1, skill: { id: 'fire_bolt',         name: 'ファイアボルト',   type: 'attack',  description: '敵1体に1.8倍の火魔法ダメージ',                      cooldownMs:  3000, mpCost: 10, autoCondition: 'always', element: 'fire' } },
    { level:  5, skill: { id: 'blizzard',          name: 'ブリザード',       type: 'attack',  description: '敵全体に1.4倍の氷魔法ダメージ',                    cooldownMs: 10000, mpCost: 18, autoCondition: 'always', element: 'ice' } },
    { level: 10, skill: { id: 'arcane_focus',      name: '魔力集中',         type: 'buff',    description: '次の攻撃スキルのダメージが2倍になる',               cooldownMs: 15000, mpCost: 12, autoCondition: 'always', buffEffects: ['focus'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'thunder_storm',     name: 'サンダーストーム', type: 'attack',  description: '敵全体に1.8倍の雷魔法ダメージ',                    cooldownMs: 12000, mpCost: 22, autoCondition: 'always', element: 'thunder' } },
    { level: 20, skill: { id: 'meteor',            name: 'メテオ',           type: 'attack', description: '敵全体に2.5倍の大火魔法ダメージ',                  cooldownMs: 30000, mpCost: 35, autoCondition: 'enemy_hp_above_75', element: 'fire' } },
    { level: 30, skill: { id: 'inferno',           name: '炎獄',             type: 'attack', description: '敵全体に3.0倍の業火ダメージ',                      cooldownMs: 35000, mpCost: 45, autoCondition: 'always', element: 'fire' } },
    { level: 40, skill: { id: 'mana_surge',        name: '魔力暴走',         type: 'buff',    description: '自身のATK↑↑＋集中',                              cooldownMs: 20000, mpCost: 25, autoCondition: 'combat_start', buffEffects: ['atk_up', 'focus'], buffTarget: 'self' } },
    { level: 55, skill: { id: 'blizzaga',          name: '冥府の吹雪',       type: 'attack', description: '敵全体に3.5倍の極氷魔法ダメージ',                  cooldownMs: 40000, mpCost: 55, autoCondition: 'always', element: 'ice' } },
    { level: 70, skill: { id: 'magic_mastery',     name: '魔法の極致',       type: 'buff',    description: '自身のATK↑↑↑＋集中（最強形態）',                 cooldownMs: 30000, mpCost: 40, autoCondition: 'combat_start', buffEffects: ['atk_up', 'focus'], buffTarget: 'self' } },
    { level: 99, skill: { id: 'mana_supernova',     name: '魔力超新星',       type: 'attack', description: '【奥義】全MPを焼き尽くす絶命の大爆発。消費MPに比例した魔力で敵全体を消滅させる。その後MP0', cooldownMs: 90000, mpCost: 99, autoCondition: 'always', element: 'fire' } },
  ],
  rogue: [
    { level:  1, skill: { id: 'stab',              name: '刺突',             type: 'attack',  description: '敵1体に1.3倍の素早い攻撃',                         cooldownMs:  2000, mpCost:  4, autoCondition: 'always' } },
    { level:  5, skill: { id: 'poison_blade',      name: 'ポイズンブレイド', type: 'debuff',  description: '敵1体に1.0倍ダメージ＋腐毒付与',                  cooldownMs:  8000, mpCost: 12, autoCondition: 'always' } },
    { level: 10, skill: { id: 'quick_step',        name: '疾歩',             type: 'buff',    description: '自身の速度↑（最大3段）・束縛解除',                 cooldownMs:  8000, mpCost:  8, autoCondition: 'always', buffEffects: ['spd_up'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'smoke_screen',      name: '煙幕',             type: 'debuff',  description: '敵全体の速度↓付与',                               cooldownMs: 12000, mpCost: 15, autoCondition: 'always' } },
    { level: 20, skill: { id: 'backstab',          name: 'バックスタブ',     type: 'attack', description: '敵1体に2.2倍の急所攻撃',                          cooldownMs: 20000, mpCost: 22, autoCondition: 'always' } },
    { level: 30, skill: { id: 'rapid_stab',        name: '連続刺突',         type: 'attack',  description: '敵1体に0.6倍×5回の超速連撃',                      cooldownMs: 18000, mpCost: 28, autoCondition: 'always' } },
    { level: 40, skill: { id: 'toxic_mist',        name: '毒霧散布',         type: 'debuff',  description: '敵全体に腐毒付与',                                 cooldownMs: 15000, mpCost: 22, autoCondition: 'always' } },
    { level: 55, skill: { id: 'shadow_clone',      name: '影分身',           type: 'buff',    description: '自身のATK↑↑＋速↑↑',                            cooldownMs: 25000, mpCost: 35, autoCondition: 'combat_start', buffEffects: ['atk_up', 'spd_up'], buffTarget: 'self' } },
    { level: 70, skill: { id: 'assassination_art', name: '暗殺術極意',       type: 'attack', description: '敵1体に3.5倍＋腐毒付与の必殺一撃',                 cooldownMs: 30000, mpCost: 40, autoCondition: 'always' } },
    { level: 99, skill: { id: 'death_gamble',       name: '死の賭け',         type: 'attack', description: '【奥義】コインを投げる。表：敵1体に15倍の確実な死の一刺。裏：完全な空振り（50%/50%のランダム）', cooldownMs: 60000, mpCost: 60, autoCondition: 'always' } },
  ],
  priest: [
    { level:  1, skill: { id: 'heal',              name: 'ヒール',           type: 'heal',    description: 'HP最低の味方のHPを15%回復',                        cooldownMs:  5000, mpCost: 12, autoCondition: 'hp_below_50' } },
    { level:  5, skill: { id: 'holy_light',        name: 'ホーリーライト',   type: 'attack',  description: '敵1体に1.6倍の光魔法ダメージ',                      cooldownMs:  8000, mpCost: 14, autoCondition: 'always', element: 'light' } },
    { level: 10, skill: { id: 'purify',            name: '浄化',             type: 'heal',    description: 'パーティ全員の状態異常をすべて回復',                 cooldownMs: 20000, mpCost: 20, autoCondition: 'always', cureEffect: 'all' } },
    { level: 15, skill: { id: 'party_regen',       name: 'リジェネ',         type: 'buff',    description: 'パーティ全員に再生付与（4行動）',                   cooldownMs: 20000, mpCost: 25, autoCondition: 'hp_below_50', buffEffects: ['regen'], buffTarget: 'party' } },
    { level: 20, skill: { id: 'resurrection',      name: 'リザレクション',   type: 'heal',    description: '戦闘不能の味方をHP25%で復活させる',                 cooldownMs: 60000, mpCost: 40, autoCondition: 'hp_below_25' } },
    { level: 30, skill: { id: 'sanctuary',         name: '聖域',             type: 'buff',    description: 'パーティ全体のDEF↑＋HP10%回復',                   cooldownMs: 25000, mpCost: 35, autoCondition: 'hp_below_50', buffEffects: ['def_up'], buffTarget: 'party' } },
    { level: 40, skill: { id: 'holy_barrier',      name: '聖なる盾',         type: 'buff',    description: 'パーティ全体に結界付与',                           cooldownMs: 35000, mpCost: 40, autoCondition: 'hp_below_50', buffEffects: ['barrier'], buffTarget: 'party' } },
    { level: 55, skill: { id: 'great_radiance',    name: '大光明',           type: 'attack', description: '敵全体に2.5倍の神聖ダメージ',                      cooldownMs: 30000, mpCost: 45, autoCondition: 'always', element: 'light' } },
    { level: 70, skill: { id: 'miracle',           name: '奇跡',             type: 'heal',    description: '戦闘不能全員をHP50%で復活＋全体回復',               cooldownMs: 90000, mpCost: 70, autoCondition: 'hp_below_25' } },
    { level: 99, skill: { id: 'martyrdom',          name: '聖者の殉教',       type: 'buff',    description: '【奥義】自身の命と引き換えに全味方のHP全回復＋全種バフ付与。発動後、自身は戦闘不能になる', cooldownMs: 90000, mpCost: 99, autoCondition: 'hp_below_25', buffEffects: ['atk_up', 'def_up', 'spd_up', 'regen', 'barrier', 'focus', 'guard'], buffTarget: 'party' } },
  ],
  ranger: [
    { level:  1, skill: { id: 'rapid_shot',        name: '連射',             type: 'attack',  description: '敵1体に1.2倍の素早い攻撃',                         cooldownMs:  2500, mpCost:  5, autoCondition: 'always' } },
    { level:  5, skill: { id: 'pierce_arrow',      name: '貫通矢',           type: 'attack',  description: '敵全体に1.0倍の貫通攻撃',                          cooldownMs: 10000, mpCost: 12, autoCondition: 'always' } },
    { level: 10, skill: { id: 'hawk_eye',          name: '鷹の目',           type: 'buff',    description: '自身の速度↑（最大3段）',                           cooldownMs:  8000, mpCost:  8, autoCondition: 'combat_start', buffEffects: ['spd_up'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'poison_arrow',      name: '毒矢',             type: 'debuff',  description: '敵1体に1.0倍ダメージ＋腐毒付与',                  cooldownMs:  8000, mpCost: 12, autoCondition: 'always' } },
    { level: 20, skill: { id: 'storm_arrow',       name: '矢の嵐',           type: 'attack', description: '敵全体に1.8倍の矢の雨',                            cooldownMs: 25000, mpCost: 25, autoCondition: 'always' } },
    { level: 30, skill: { id: 'multi_arrow',       name: '連撃矢',           type: 'attack',  description: '敵1体に0.8倍×4回の連続射撃',                      cooldownMs: 18000, mpCost: 22, autoCondition: 'always' } },
    { level: 40, skill: { id: 'focused_shot',      name: '集中射撃',         type: 'buff',    description: '自身のATK↑↑',                                    cooldownMs: 20000, mpCost: 25, autoCondition: 'combat_start', buffEffects: ['atk_up'], buffTarget: 'self' } },
    { level: 55, skill: { id: 'gale_rapid',        name: '疾風連射',         type: 'attack',  description: '敵1体に0.7倍×6回の超高速射撃',                    cooldownMs: 25000, mpCost: 35, autoCondition: 'always' } },
    { level: 70, skill: { id: 'divine_shot',       name: '神速射',           type: 'attack', description: '敵1体に3.5倍の必中射撃',                          cooldownMs: 30000, mpCost: 40, autoCondition: 'always' } },
    { level: 99, skill: { id: 'void_shot',          name: '虚無の一矢',       type: 'attack', description: '【奥義】防御を完全に無視する神速の射撃。敵1体のDEF・バリアを完全貫通して固定致命ダメージを与える', cooldownMs: 90000, mpCost: 85, autoCondition: 'always' } },
  ],
  knight: [
    { level:  1, skill: { id: 'taunt',             name: '挑発',             type: 'debuff',  description: '敵1体に封守付与（防御を崩す）',                    cooldownMs:  8000, mpCost:  8, autoCondition: 'combat_start' } },
    { level:  5, skill: { id: 'iron_wall',         name: '鉄壁',             type: 'buff',    description: '自身のDEF↑（最大3段）',                           cooldownMs:  8000, mpCost: 10, autoCondition: 'hp_below_50', buffEffects: ['def_up'], buffTarget: 'self' } },
    { level: 10, skill: { id: 'bulwark',           name: '要塞',             type: 'buff',    description: 'パーティ全体のDEF↑',                              cooldownMs: 20000, mpCost: 25, autoCondition: 'combat_start', buffEffects: ['def_up'], buffTarget: 'party' } },
    { level: 15, skill: { id: 'holy_shield',       name: '聖盾',             type: 'buff',    description: '自身に結界（次のダメージを1回無効）',               cooldownMs: 20000, mpCost: 15, autoCondition: 'hp_below_50', buffEffects: ['barrier'], buffTarget: 'self' } },
    { level: 20, skill: { id: 'counter_stance',    name: 'カウンター',       type: 'buff',    description: '自身のDEF↑↑＋集中',                              cooldownMs: 18000, mpCost: 20, autoCondition: 'hp_below_50', buffEffects: ['def_up', 'focus'], buffTarget: 'self' } },
    { level: 30, skill: { id: 'iron_charge',       name: '鉄壁突撃',         type: 'attack',  description: '敵1体に1.8倍ダメージ＋自身DEF↑',                  cooldownMs: 20000, mpCost: 22, autoCondition: 'always' } },
    { level: 40, skill: { id: 'guardian_oath',     name: '守護の誓い',       type: 'buff',    description: 'パーティ全体に結界＋DEF↑↑',                       cooldownMs: 40000, mpCost: 40, autoCondition: 'hp_below_50', buffEffects: ['barrier', 'def_up'], buffTarget: 'party' } },
    { level: 55, skill: { id: 'invincible_fortress', name: '無敵の城',       type: 'buff',    description: '自身にDEF↑↑↑＋結界＋再生',                       cooldownMs: 35000, mpCost: 40, autoCondition: 'hp_below_25', buffEffects: ['def_up', 'barrier', 'regen'], buffTarget: 'self' } },
    { level: 70, skill: { id: 'holy_knight_guard', name: '聖騎士の守護',     type: 'buff',    description: 'パーティ全体のHP10%回復＋DEF↑↑',                  cooldownMs: 40000, mpCost: 45, autoCondition: 'hp_below_50', buffEffects: ['def_up'], buffTarget: 'party' } },
    { level: 99, skill: { id: 'guardian_sacrifice', name: '守護の殉教',       type: 'buff',    description: '【奥義】自身のHP30%を犠牲に全味方に結界×3＋DEF↑↑↑付与。この盾に守られよ、己は人柱となる', cooldownMs: 90000, mpCost: 99, autoCondition: 'hp_below_50', buffEffects: ['barrier', 'def_up'], buffTarget: 'party' } },
  ],
  wizard: [
    { level:  1, skill: { id: 'mana_bolt',         name: '魔力弾',           type: 'attack',  description: '敵1体に2.0倍の雷魔法ダメージ',                      cooldownMs:  3000, mpCost: 12, autoCondition: 'always', element: 'thunder' } },
    { level:  5, skill: { id: 'arcane_nova',        name: 'アルカナノヴァ',   type: 'attack',  description: '敵全体に1.6倍の雷魔法ダメージ',                    cooldownMs: 12000, mpCost: 22, autoCondition: 'always', element: 'thunder' } },
    { level: 10, skill: { id: 'concentration',     name: '集中',             type: 'buff',    description: '次の攻撃スキルのダメージが2倍になる',               cooldownMs: 15000, mpCost: 12, autoCondition: 'always', buffEffects: ['focus'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'chain_lightning',   name: 'チェーンライトニング', type: 'attack', description: '敵全体に1.8倍の連鎖雷撃ダメージ',               cooldownMs: 15000, mpCost: 28, autoCondition: 'always', element: 'thunder' } },
    { level: 20, skill: { id: 'grand_magic',       name: '大魔法',           type: 'attack', description: '敵全体に3.0倍の超高威力雷魔法',                    cooldownMs: 40000, mpCost: 50, autoCondition: 'enemy_hp_above_75', element: 'thunder' } },
    { level: 30, skill: { id: 'flash',             name: '閃光',             type: 'attack', description: '敵全体に2.0倍の光魔法ダメージ',                    cooldownMs: 25000, mpCost: 35, autoCondition: 'always', element: 'light' } },
    { level: 40, skill: { id: 'mana_explosion',    name: '魔力爆発',         type: 'attack', description: '敵全体に2.8倍の雷魔法爆発ダメージ',                cooldownMs: 35000, mpCost: 45, autoCondition: 'always', element: 'thunder' } },
    { level: 55, skill: { id: 'ultra_magic',       name: '極大魔法',         type: 'attack', description: '敵全体に4.0倍の雷魔法',                            cooldownMs: 50000, mpCost: 65, autoCondition: 'enemy_hp_above_75', element: 'thunder' } },
    { level: 70, skill: { id: 'spacetime_magic',   name: '時空魔法',         type: 'buff',    description: '自身のATK↑↑↑＋集中（魔法師の頂点）',             cooldownMs: 35000, mpCost: 45, autoCondition: 'combat_start', buffEffects: ['atk_up', 'focus'], buffTarget: 'self' } },
    { level: 99, skill: { id: 'thunder_god_burst',  name: '雷神自爆',         type: 'attack', description: '【奥義】全MPを一瞬で放電する自己破壊。消費MP×12の超電圧を敵全体に浴びせ、発動後自身は気絶（MP0）', cooldownMs: 90000, mpCost: 99, autoCondition: 'always', element: 'thunder' } },
  ],
  assassin: [
    { level:  1, skill: { id: 'shadow_slash',      name: '影斬り',           type: 'attack',  description: '敵1体に1.8倍の素早い暗殺',                         cooldownMs:  2500, mpCost:  8, autoCondition: 'always' } },
    { level:  5, skill: { id: 'venom_strike',      name: '毒牙',             type: 'debuff',  description: '敵1体に1.2倍ダメージ＋腐毒付与',                  cooldownMs:  8000, mpCost: 14, autoCondition: 'always' } },
    { level: 10, skill: { id: 'shadow_step',       name: '影走り',           type: 'buff',    description: '自身の速度↑（最大3段）・束縛解除',                 cooldownMs:  8000, mpCost:  8, autoCondition: 'always', buffEffects: ['spd_up'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'smoke_bomb',        name: '煙幕弾',           type: 'debuff',  description: '敵全体の速度↓付与',                               cooldownMs: 12000, mpCost: 15, autoCondition: 'always' } },
    { level: 20, skill: { id: 'instant_kill',      name: '一閃',             type: 'attack', description: '敵1体に3.0倍の致命的一撃',                         cooldownMs: 25000, mpCost: 30, autoCondition: 'always' } },
    { level: 30, skill: { id: 'double_slash',      name: '二連斬',           type: 'attack',  description: '敵1体に1.4倍×2回の連続斬撃',                      cooldownMs: 15000, mpCost: 20, autoCondition: 'always' } },
    { level: 40, skill: { id: 'poison_fog',        name: '毒霧',             type: 'debuff',  description: '敵全体に腐毒付与',                                 cooldownMs: 15000, mpCost: 22, autoCondition: 'always' } },
    { level: 55, skill: { id: 'lethal_blade',      name: '絶命の刃',         type: 'attack', description: '敵1体に3.8倍の必殺一撃',                          cooldownMs: 30000, mpCost: 40, autoCondition: 'always' } },
    { level: 70, skill: { id: 'death_dance',       name: '死の舞踏',         type: 'attack', description: '敵1体に2.0倍×3回＋速↑',                          cooldownMs: 30000, mpCost: 40, autoCondition: 'always' } },
    { level: 99, skill: { id: 'evaporate',          name: '蒸発',             type: 'attack', description: '【奥義】速度の到達点。敵の防御・バリア・状態を全て無視した絶対暗殺。ただし発動後、自身は虚脱状態', cooldownMs: 60000, mpCost: 80, autoCondition: 'always' } },
  ],
  paladin: [
    { level:  1, skill: { id: 'holy_strike',       name: '聖剣撃',           type: 'attack',  description: '敵1体に1.4倍の光ダメージ',                         cooldownMs:  4000, mpCost:  8, autoCondition: 'always', element: 'light' } },
    { level:  5, skill: { id: 'divine_aura',       name: '神聖オーラ',       type: 'heal',    description: 'パーティのHPを10%回復',                            cooldownMs: 15000, mpCost: 20, autoCondition: 'hp_below_50' } },
    { level: 10, skill: { id: 'holy_regen',        name: '聖なる再生',       type: 'buff',    description: '自身に再生（4行動・毎行動MaxHP5%回復）',            cooldownMs: 15000, mpCost: 15, autoCondition: 'hp_below_50', buffEffects: ['regen'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'judgment',          name: '審判',             type: 'attack', description: '敵全体に2.0倍の神聖ダメージ',                      cooldownMs: 35000, mpCost: 40, autoCondition: 'always', element: 'light' } },
    { level: 20, skill: { id: 'divine_guard',      name: '神盾',             type: 'buff',    description: '自身に結界＋DEF↑',                                 cooldownMs: 25000, mpCost: 20, autoCondition: 'hp_below_25', buffEffects: ['barrier', 'def_up'], buffTarget: 'self' } },
    { level: 30, skill: { id: 'holy_storm',        name: '聖なる嵐',         type: 'attack', description: '敵全体に2.8倍の光ダメージ',                        cooldownMs: 40000, mpCost: 50, autoCondition: 'always', element: 'light' } },
    { level: 40, skill: { id: 'divine_revelation', name: '天啓',             type: 'buff',    description: 'パーティ全体のATK↑＋HP10%回復',                   cooldownMs: 30000, mpCost: 35, autoCondition: 'combat_start', buffEffects: ['atk_up'], buffTarget: 'party' } },
    { level: 55, skill: { id: 'holy_blade_art',    name: '聖剣技',           type: 'attack', description: '敵1体に3.5倍の光ダメージ＋自己回復',               cooldownMs: 35000, mpCost: 45, autoCondition: 'always', element: 'light' } },
    { level: 70, skill: { id: 'cross_light',       name: '十字聖光',         type: 'attack', description: '敵全体に3.2倍の光ダメージ＋パーティ再生',          cooldownMs: 50000, mpCost: 55, autoCondition: 'always', element: 'light' } },
    { level: 99, skill: { id: 'divine_judgment',   name: '天の裁き',         type: 'attack', description: '【奥義】敵の現在HPの30%を問答無用で奪う神の裁定。DEF完全無視・割合固定ダメージで全ての敵に等しく執行', cooldownMs: 90000, mpCost: 99, autoCondition: 'always', element: 'light' } },
  ],
  bard: [
    { level:  1, skill: { id: 'war_song',          name: '激励の歌',         type: 'buff',    description: '自身のATK↑（最大3段）',                           cooldownMs:  8000, mpCost: 10, autoCondition: 'combat_start', buffEffects: ['atk_up'], buffTarget: 'self' } },
    { level:  5, skill: { id: 'lullaby',           name: '子守唄',           type: 'debuff',  description: '敵全体の攻撃力を封じる（封力付与）',               cooldownMs: 15000, mpCost: 15, autoCondition: 'always' } },
    { level: 10, skill: { id: 'speed_song',        name: '疾風の歌',         type: 'buff',    description: '自身の速度↑（最大3段）',                           cooldownMs:  8000, mpCost: 10, autoCondition: 'always', buffEffects: ['spd_up'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'healing_song',      name: '回復の歌',         type: 'heal',    description: 'パーティ全体のHPを15%回復',                        cooldownMs: 20000, mpCost: 25, autoCondition: 'hp_below_50' } },
    { level: 20, skill: { id: 'heroic_tale',       name: '英雄譚',           type: 'buff',    description: 'パーティ全体のATK↑・速↑',                         cooldownMs: 45000, mpCost: 40, autoCondition: 'combat_start', buffEffects: ['atk_up', 'spd_up'], buffTarget: 'party' } },
    { level: 30, skill: { id: 'defense_song',      name: '守りの歌',         type: 'buff',    description: 'パーティ全体のDEF↑',                              cooldownMs: 25000, mpCost: 30, autoCondition: 'hp_below_50', buffEffects: ['def_up'], buffTarget: 'party' } },
    { level: 40, skill: { id: 'enchanting_melody', name: '魅惑の旋律',       type: 'debuff',  description: '敵全体の封力＋封守付与',                           cooldownMs: 20000, mpCost: 28, autoCondition: 'always' } },
    { level: 55, skill: { id: 'battle_chorus',     name: '鼓舞大合唱',       type: 'buff',    description: 'パーティ全体のATK↑↑＋速↑',                       cooldownMs: 50000, mpCost: 50, autoCondition: 'combat_start', buffEffects: ['atk_up', 'spd_up'], buffTarget: 'party' } },
    { level: 70, skill: { id: 'sages_poem',        name: '賢者の詩',         type: 'buff',    description: 'パーティ全体のATK↑・DEF↑・速↑',                  cooldownMs: 55000, mpCost: 55, autoCondition: 'combat_start', buffEffects: ['atk_up', 'def_up', 'spd_up'], buffTarget: 'party' } },
    { level: 99, skill: { id: 'grand_madness',     name: '狂乱の大合奏',     type: 'buff',    description: '【奥義】全ての音を同時に奏でる狂気の演奏。全味方に全種バフを付与する。混沌のあまり自身は気絶', cooldownMs: 90000, mpCost: 99, autoCondition: 'combat_start', buffEffects: ['atk_up', 'def_up', 'spd_up', 'regen', 'barrier', 'focus', 'guard'], buffTarget: 'party' } },
  ],
  berserker: [
    { level:  1, skill: { id: 'berserk',           name: '暴走',             type: 'buff',    description: '自身のATK↑（最大3段）',                           cooldownMs:  6000, mpCost:  5, autoCondition: 'combat_start', buffEffects: ['atk_up'], buffTarget: 'self' } },
    { level:  5, skill: { id: 'rampage',           name: '無双乱打',         type: 'attack',  description: '敵1体に0.8倍×3回攻撃',                            cooldownMs: 10000, mpCost: 12, autoCondition: 'always' } },
    { level: 10, skill: { id: 'war_frenzy',        name: '戦慄',             type: 'buff',    description: '自身のATK↑↑＋集中',                              cooldownMs: 20000, mpCost: 20, autoCondition: 'hp_below_50', buffEffects: ['atk_up', 'focus'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'frenzy',            name: '狂乱',             type: 'buff',    description: '自身のATK↑↑↑（極限形態）',                       cooldownMs: 25000, mpCost: 25, autoCondition: 'hp_below_25', buffEffects: ['atk_up'], buffTarget: 'self' } },
    { level: 20, skill: { id: 'blood_frenzy',      name: '血の狂乱',         type: 'attack', description: '敵1体に3.5倍の超威力攻撃',                         cooldownMs: 30000, mpCost: 25, autoCondition: 'always' } },
    { level: 30, skill: { id: 'death_blow',        name: '死狂い',           type: 'attack',  description: '敵1体に1.0倍×5回の乱打',                          cooldownMs: 22000, mpCost: 28, autoCondition: 'always' } },
    { level: 40, skill: { id: 'oni_form',          name: '鬼神化',           type: 'buff',    description: '自身のATK↑↑＋速↑（DEF一時低下）',                cooldownMs: 30000, mpCost: 30, autoCondition: 'combat_start', buffEffects: ['atk_up', 'spd_up'], buffTarget: 'self' } },
    { level: 55, skill: { id: 'destruction_fist',  name: '滅殺拳',           type: 'attack', description: '敵1体に4.5倍の必殺攻撃',                          cooldownMs: 40000, mpCost: 45, autoCondition: 'always' } },
    { level: 70, skill: { id: 'avatar_destruction', name: '破壊の化身',      type: 'attack', description: '敵全体に3.2倍の暴力的攻撃',                        cooldownMs: 45000, mpCost: 50, autoCondition: 'always' } },
    { level: 99, skill: { id: 'life_combustion',   name: '命燃焼',           type: 'attack', description: '【奥義】全ての命を一撃に込める。自身HP→1にして失った生命の分だけ、敵1体に破壊的打撃を叩き込む', cooldownMs: 75000, mpCost: 30, autoCondition: 'hp_below_50' } },
  ],
  witch: [
    { level:  1, skill: { id: 'curse',             name: '呪縛',             type: 'debuff',  description: '敵1体に封力＋封守付与',                            cooldownMs:  6000, mpCost: 10, autoCondition: 'combat_start' } },
    { level:  5, skill: { id: 'poison_mist',       name: '毒霧',             type: 'debuff',  description: '敵全体に腐毒付与',                                 cooldownMs: 12000, mpCost: 18, autoCondition: 'always' } },
    { level: 10, skill: { id: 'hex_bind',          name: '縛呪',             type: 'debuff',  description: '敵全体に束縛付与',                                 cooldownMs: 15000, mpCost: 20, autoCondition: 'always' } },
    { level: 15, skill: { id: 'dark_hex',          name: '暗黒呪',           type: 'debuff',  description: '敵全体のATK↓・DEF↓付与',                         cooldownMs: 18000, mpCost: 25, autoCondition: 'always' } },
    { level: 20, skill: { id: 'black_magic',       name: '黒魔術',           type: 'attack', description: '敵1体に2.5倍の呪詛ダメージ',                       cooldownMs: 25000, mpCost: 35, autoCondition: 'always', element: 'dark' } },
    { level: 30, skill: { id: 'death_kiss',        name: '死の接吻',         type: 'attack', description: '敵1体に2.2倍闇ダメージ＋全体腐毒付与',             cooldownMs: 28000, mpCost: 38, autoCondition: 'always', element: 'dark' } },
    { level: 40, skill: { id: 'curse_explosion',   name: '呪詛爆発',         type: 'attack', description: '敵全体に2.8倍の呪詛爆発ダメージ',                  cooldownMs: 35000, mpCost: 48, autoCondition: 'always', element: 'dark' } },
    { level: 55, skill: { id: 'underworld_bind',   name: '冥府の縛り',       type: 'debuff',  description: '敵全体に封力・封守・束縛・腐毒を一括付与',         cooldownMs: 35000, mpCost: 45, autoCondition: 'always' } },
    { level: 70, skill: { id: 'witch_feast',       name: '魔女の宴',         type: 'attack', description: '敵全体に3.5倍の闇ダメージ＋全デバフ',              cooldownMs: 50000, mpCost: 60, autoCondition: 'always', element: 'dark' } },
    { level: 99, skill: { id: 'mutual_curse',      name: '道連れの呪い',     type: 'attack', description: '【奥義】敵1体の現在HPと等量のダメージを互いに受け合う相打ち呪詛。「一緒に死のう」という呪い', cooldownMs: 90000, mpCost: 60, autoCondition: 'always', element: 'dark' } },
  ],
  monk: [
    { level:  1, skill: { id: 'combo_strike',      name: '連打',             type: 'attack',  description: '敵1体に0.7倍×3回の連打',                          cooldownMs:  3000, mpCost:  6, autoCondition: 'always' } },
    { level:  5, skill: { id: 'ki_focus',          name: '気功',             type: 'buff',    description: '自身のATK↑・速↑（最大3段）',                      cooldownMs: 10000, mpCost: 15, autoCondition: 'combat_start', buffEffects: ['atk_up', 'spd_up'], buffTarget: 'self' } },
    { level: 10, skill: { id: 'inner_focus',       name: '内なる力',         type: 'buff',    description: '自身に集中（次の攻撃×2）',                         cooldownMs: 12000, mpCost: 10, autoCondition: 'always', buffEffects: ['focus'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'iron_body',         name: '鉄山靠',           type: 'buff',    description: '自身のDEF↑↑',                                    cooldownMs: 15000, mpCost: 15, autoCondition: 'hp_below_50', buffEffects: ['def_up'], buffTarget: 'self' } },
    { level: 20, skill: { id: 'heavenly_fist',     name: '天空拳',           type: 'attack', description: '敵1体に2.8倍の必殺拳',                            cooldownMs: 25000, mpCost: 28, autoCondition: 'always' } },
    { level: 30, skill: { id: 'hundred_fists',     name: '百烈拳',           type: 'attack',  description: '敵1体に0.5倍×6回の超高速連打',                    cooldownMs: 22000, mpCost: 30, autoCondition: 'always' } },
    { level: 40, skill: { id: 'ki_explosion',      name: '気功爆発',         type: 'attack', description: '敵全体に2.2倍の気弾爆発',                          cooldownMs: 30000, mpCost: 38, autoCondition: 'always' } },
    { level: 55, skill: { id: 'selfless_mastery',  name: '無我の境地',       type: 'buff',    description: '自身のATK↑↑↑＋速↑↑（極限開放）',               cooldownMs: 35000, mpCost: 45, autoCondition: 'combat_start', buffEffects: ['atk_up', 'spd_up'], buffTarget: 'self' } },
    { level: 70, skill: { id: 'mastery_fist',      name: '極意拳',           type: 'attack', description: '敵1体に4.2倍の究極必殺拳',                         cooldownMs: 40000, mpCost: 50, autoCondition: 'always' } },
    { level: 99, skill: { id: 'limit_break_fist',  name: '絶境の一拳',       type: 'attack', description: '【奥義】HP25%以下の極限状態でのみ発動する30倍の必殺拳。死の淵から絞り出す。発動後、自身は虚脱状態', cooldownMs: 75000, mpCost: 99, autoCondition: 'hp_below_25' } },
  ],
  druid: [
    { level:  1, skill: { id: 'natures_gift',      name: '自然の恵み',       type: 'heal',    description: 'HP最低の味方のHPを20%回復',                        cooldownMs:  6000, mpCost: 15, autoCondition: 'hp_below_50' } },
    { level:  5, skill: { id: 'thorn_bind',        name: '茨の鎖',           type: 'debuff',  description: '敵1体に封力＋束縛付与',                            cooldownMs: 10000, mpCost: 18, autoCondition: 'always' } },
    { level: 10, skill: { id: 'detox',             name: '解毒',             type: 'heal',    description: 'パーティ全員の腐毒を解除',                          cooldownMs: 12000, mpCost: 12, autoCondition: 'always', cureEffect: 'poison' } },
    { level: 15, skill: { id: 'earth_guard',       name: '大地の守護',       type: 'buff',    description: 'パーティ全体のDEF↑',                              cooldownMs: 20000, mpCost: 25, autoCondition: 'hp_below_50', buffEffects: ['def_up'], buffTarget: 'party' } },
    { level: 20, skill: { id: 'storm_blessing',    name: '嵐の加護',         type: 'buff',    description: 'パーティ全体のATK↑・DEF↑',                        cooldownMs: 40000, mpCost: 40, autoCondition: 'combat_start', buffEffects: ['atk_up', 'def_up'], buffTarget: 'party' } },
    { level: 30, skill: { id: 'nature_heal',       name: '自然の癒し',       type: 'buff',    description: 'パーティ全員に再生付与',                           cooldownMs: 25000, mpCost: 30, autoCondition: 'hp_below_50', buffEffects: ['regen'], buffTarget: 'party' } },
    { level: 40, skill: { id: 'root_bind',         name: '木の根の縛り',     type: 'debuff',  description: '敵全体に束縛付与',                                 cooldownMs: 18000, mpCost: 25, autoCondition: 'always' } },
    { level: 55, skill: { id: 'earth_rage',        name: '大地の怒り',       type: 'attack', description: '敵全体に2.5倍の大地爆発ダメージ',                  cooldownMs: 35000, mpCost: 45, autoCondition: 'always' } },
    { level: 70, skill: { id: 'nature_power',      name: '大自然の力',       type: 'buff',    description: 'パーティ全体のATK↑↑＋再生付与',                   cooldownMs: 45000, mpCost: 50, autoCondition: 'combat_start', buffEffects: ['atk_up', 'regen'], buffTarget: 'party' } },
    { level: 99, skill: { id: 'reincarnation',     name: '大地の輪廻',       type: 'heal',    description: '【奥義】自身を大地に還す自己犠牲。全戦闘不能の仲間を全快で蘇生し、生存者全員に永続再生を付与する', cooldownMs: 90000, mpCost: 99, autoCondition: 'hp_below_25' } },
  ],
  dancer: [
    { level:  1, skill: { id: 'war_dance',         name: '戦舞',             type: 'buff',    description: '自身の速度↑（最大3段）',                           cooldownMs:  8000, mpCost: 12, autoCondition: 'combat_start', buffEffects: ['spd_up'], buffTarget: 'self' } },
    { level:  5, skill: { id: 'illusion_dance',    name: '幻惑の舞',         type: 'debuff',  description: '敵全体に束縛付与',                                 cooldownMs: 12000, mpCost: 15, autoCondition: 'always' } },
    { level: 10, skill: { id: 'healing_dance',     name: '癒しの舞',         type: 'buff',    description: '自身に再生（4行動）',                              cooldownMs: 15000, mpCost: 15, autoCondition: 'hp_below_50', buffEffects: ['regen'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'allure_dance',      name: '誘惑の舞',         type: 'debuff',  description: '敵全体の封力付与',                                 cooldownMs: 15000, mpCost: 20, autoCondition: 'always' } },
    { level: 20, skill: { id: 'celestial_dance',   name: '天舞',             type: 'buff',    description: 'パーティ全体の速↑・ATK↑',                         cooldownMs: 50000, mpCost: 45, autoCondition: 'combat_start', buffEffects: ['spd_up', 'atk_up'], buffTarget: 'party' } },
    { level: 30, skill: { id: 'charming_dance',    name: '魅惑の舞',         type: 'debuff',  description: '敵全体の封力・束縛付与',                           cooldownMs: 20000, mpCost: 28, autoCondition: 'always' } },
    { level: 40, skill: { id: 'blade_dance',       name: '死の舞い',         type: 'attack', description: '敵全体に1.5倍ダメージ＋束縛付与',                  cooldownMs: 30000, mpCost: 35, autoCondition: 'always' } },
    { level: 55, skill: { id: 'storm_dance',       name: '嵐の舞い',         type: 'buff',    description: 'パーティ全体のATK↑↑・速↑↑',                     cooldownMs: 55000, mpCost: 55, autoCondition: 'combat_start', buffEffects: ['atk_up', 'spd_up'], buffTarget: 'party' } },
    { level: 70, skill: { id: 'divine_dance',      name: '神舞',             type: 'attack', description: '敵全体に2.8倍ダメージ＋パーティ全体ATK↑',          cooldownMs: 50000, mpCost: 55, autoCondition: 'always' } },
    { level: 99, skill: { id: 'chaos_dance',       name: '混沌の舞踏',       type: 'buff',    description: '【奥義】秩序と混沌を同時に踊る禁断の舞。全敵に全デバフ、全味方に全種バフを一瞬で付与する', cooldownMs: 90000, mpCost: 99, autoCondition: 'always', buffEffects: ['atk_up', 'def_up', 'spd_up', 'regen', 'barrier', 'focus', 'guard'], buffTarget: 'party' } },
  ],
  dark_knight: [
    { level:  1, skill: { id: 'dark_slash',        name: '闇斬り',           type: 'attack',  description: '敵1体に1.6倍の闇属性ダメージ',                      cooldownMs:  3500, mpCost: 10, autoCondition: 'always', element: 'dark' } },
    { level:  5, skill: { id: 'life_drain',        name: '生命吸収',         type: 'attack', description: '敵1体にダメージ＋自身HP回復',                       cooldownMs: 12000, mpCost: 20, autoCondition: 'hp_below_50', element: 'dark' } },
    { level: 10, skill: { id: 'dark_aura',         name: '闇オーラ',         type: 'buff',    description: '自身のATK↑・集中',                                 cooldownMs: 15000, mpCost: 15, autoCondition: 'combat_start', buffEffects: ['atk_up', 'focus'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'soul_cry',          name: '魂の叫び',         type: 'buff',    description: '自身のATK↑↑',                                    cooldownMs: 20000, mpCost: 20, autoCondition: 'hp_below_50', buffEffects: ['atk_up'], buffTarget: 'self' } },
    { level: 20, skill: { id: 'dark_sword',        name: '暗黒剣',           type: 'attack', description: '敵全体に2.0倍の闇爆発ダメージ',                    cooldownMs: 30000, mpCost: 40, autoCondition: 'always', element: 'dark' } },
    { level: 30, skill: { id: 'dark_blade_art',    name: '闇の剣技',         type: 'attack', description: '敵1体に2.8倍の闇ダメージ＋自己回復',               cooldownMs: 28000, mpCost: 35, autoCondition: 'always', element: 'dark' } },
    { level: 40, skill: { id: 'despair_strike',    name: '絶望の一撃',       type: 'attack', description: '敵1体に3.2倍ダメージ＋全体封守付与',               cooldownMs: 35000, mpCost: 45, autoCondition: 'always', element: 'dark' } },
    { level: 55, skill: { id: 'dark_frenzy',       name: '闇の暴走',         type: 'buff',    description: '自身のATK↑↑↑・速↑',                             cooldownMs: 35000, mpCost: 40, autoCondition: 'hp_below_50', buffEffects: ['atk_up', 'spd_up'], buffTarget: 'self' } },
    { level: 70, skill: { id: 'netherworld_blade', name: '冥界剣',           type: 'attack', description: '敵1体に4.2倍の冥界ダメージ＋パーティATK↑',         cooldownMs: 45000, mpCost: 55, autoCondition: 'always', element: 'dark' } },
    { level: 99, skill: { id: 'dark_pact',          name: '漆黒の契約',       type: 'attack', description: '【奥義】命を代価に払う禁断の契約。自身の最大HP50%を失い、全敵に漆黒の絶対破壊（DEF無視）を与える', cooldownMs: 90000, mpCost: 80, autoCondition: 'hp_below_50', element: 'dark' } },
  ],
  necromancer: [
    { level:  1, skill: { id: 'death_curse',       name: '死の呪い',         type: 'debuff',  description: '敵1体に封力＋封守付与',                            cooldownMs:  8000, mpCost: 15, autoCondition: 'combat_start', element: 'dark' } },
    { level:  5, skill: { id: 'soul_steal',        name: '魂奪取',           type: 'attack', description: '敵1体にダメージ＋MP吸収',                          cooldownMs: 12000, mpCost: 20, autoCondition: 'always', element: 'dark' } },
    { level: 10, skill: { id: 'undead_army',       name: '死霊軍団',         type: 'attack', description: '敵全体に2.2倍の呪詛ダメージ',                      cooldownMs: 40000, mpCost: 50, autoCondition: 'always', element: 'dark' } },
    { level: 15, skill: { id: 'decay_mist',        name: '腐敗の霧',         type: 'debuff',  description: '敵全体に腐毒＋封力付与',                           cooldownMs: 15000, mpCost: 25, autoCondition: 'always', element: 'dark' } },
    { level: 20, skill: { id: 'finger_of_death',   name: '死の指',           type: 'attack', description: '敵1体に2.8倍の呪詛ダメージ（DEF無視）',            cooldownMs: 30000, mpCost: 38, autoCondition: 'always', element: 'dark' } },
    { level: 30, skill: { id: 'legion_of_dead',    name: '屍の軍勢',         type: 'attack', description: '敵全体に2.5倍の闇ダメージ＋ATK↓',                 cooldownMs: 40000, mpCost: 50, autoCondition: 'always', element: 'dark' } },
    { level: 40, skill: { id: 'soul_harvest',      name: '魂の収穫',         type: 'attack', description: '敵全体にダメージ＋自身HP・MP大回復',               cooldownMs: 40000, mpCost: 45, autoCondition: 'hp_below_50', element: 'dark' } },
    { level: 55, skill: { id: 'dance_of_death',    name: '死の舞い',         type: 'attack', description: '敵全体に3.2倍の闇ダメージ＋全デバフ',              cooldownMs: 50000, mpCost: 60, autoCondition: 'always', element: 'dark' } },
    { level: 70, skill: { id: 'lord_of_hades',     name: '黄泉の王',         type: 'attack', description: '敵1体に5.0倍の冥界ダメージ＋パーティATK↑',         cooldownMs: 55000, mpCost: 65, autoCondition: 'always', element: 'dark' } },
    { level: 99, skill: { id: 'all_in_death',       name: '全員道連れ',       type: 'attack', description: '【奥義】全味方を生贄に捧げる禁術。死した仲間の数×3000の冥府の力で全敵を葬る。代償は全滅', cooldownMs: 90000, mpCost: 99, autoCondition: 'hp_below_25', element: 'dark' } },
  ],
  sage: [
    { level:  1, skill: { id: 'elemental_shot',    name: '元素魔法',         type: 'attack',  description: '敵1体に1.7倍の光魔法ダメージ',                      cooldownMs:  3500, mpCost: 12, autoCondition: 'always', element: 'light' } },
    { level:  5, skill: { id: 'grand_heal',        name: '大回復',           type: 'heal',    description: 'パーティ全体のHPを20%回復',                        cooldownMs: 20000, mpCost: 30, autoCondition: 'hp_below_50' } },
    { level: 10, skill: { id: 'full_purify',       name: '完全浄化',         type: 'heal',    description: 'パーティ全員の全状態異常を回復',                   cooldownMs: 30000, mpCost: 30, autoCondition: 'always', cureEffect: 'all' } },
    { level: 15, skill: { id: 'star_judgment',     name: '星の裁き',         type: 'attack',  description: '敵全体に2.0倍の光魔法ダメージ',                    cooldownMs: 20000, mpCost: 30, autoCondition: 'always', element: 'light' } },
    { level: 20, skill: { id: 'cosmic_law',        name: '宇宙の理',         type: 'attack', description: '敵全体に2.8倍の光究極魔法',                        cooldownMs: 45000, mpCost: 60, autoCondition: 'enemy_hp_above_75', element: 'light' } },
    { level: 30, skill: { id: 'time_sand',         name: '時の砂',           type: 'debuff',  description: '敵全体の速度↓付与',                               cooldownMs: 20000, mpCost: 28, autoCondition: 'always' } },
    { level: 40, skill: { id: 'omni_magic',        name: '万能魔法',         type: 'attack', description: '敵全体に2.5倍ダメージ＋パーティHP15%回復',         cooldownMs: 40000, mpCost: 55, autoCondition: 'always', element: 'light' } },
    { level: 55, skill: { id: 'ultimate_cure',     name: '究極治癒',         type: 'heal',    description: 'パーティ全体のHP全回復',                           cooldownMs: 90000, mpCost: 80, autoCondition: 'hp_below_25' } },
    { level: 70, skill: { id: 'stellar_arts',      name: '星霊術',           type: 'attack', description: '敵全体に4.0倍の星霊魔法＋パーティATK↑',           cooldownMs: 55000, mpCost: 65, autoCondition: 'always', element: 'light' } },
    { level: 99, skill: { id: 'time_stop',          name: '時間停止',         type: 'debuff',  description: '【奥義】時を止める究極魔法。次の90秒間、全ての敵の行動を完全に封印する。ダメージはない', cooldownMs: 120000, mpCost: 99, autoCondition: 'always' } },
  ],
  summoner: [
    { level:  1, skill: { id: 'summon',            name: '召喚',             type: 'attack',  description: '魔獣を召喚して敵1体を攻撃（1.2倍）',               cooldownMs:  4000, mpCost: 12, autoCondition: 'always' } },
    { level:  5, skill: { id: 'beast_rush',        name: '猛攻命令',         type: 'attack',  description: '召喚獣が敵全体に1.2倍攻撃',                        cooldownMs: 15000, mpCost: 22, autoCondition: 'always' } },
    { level: 10, skill: { id: 'beast_aura',        name: '獣の加護',         type: 'buff',    description: '自身のATK↑・速↑',                                 cooldownMs: 15000, mpCost: 15, autoCondition: 'combat_start', buffEffects: ['atk_up', 'spd_up'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'fire_spirit',       name: '炎の精霊',         type: 'attack', description: '炎の精霊が敵1体に2.0倍の火ダメージ',               cooldownMs: 20000, mpCost: 28, autoCondition: 'always', element: 'fire' } },
    { level: 20, skill: { id: 'legend_summon',     name: '伝説の召喚',       type: 'attack', description: '伝説の獣を召喚、敵全体に2.5倍',                    cooldownMs: 40000, mpCost: 50, autoCondition: 'enemy_hp_above_75' } },
    { level: 30, skill: { id: 'beast_horde',       name: '獣の群れ',         type: 'attack',  description: '敵1体に1.0倍×5回の獣の連続攻撃',                  cooldownMs: 28000, mpCost: 35, autoCondition: 'always' } },
    { level: 40, skill: { id: 'ice_spirit',        name: '氷の精霊',         type: 'attack', description: '氷の精霊が敵全体に2.5倍の氷ダメージ',              cooldownMs: 35000, mpCost: 45, autoCondition: 'always', element: 'ice' } },
    { level: 55, skill: { id: 'divine_beast',      name: '神獣降臨',         type: 'attack', description: '神獣が敵1体に3.8倍の攻撃＋自身ATK↑↑',            cooldownMs: 45000, mpCost: 55, autoCondition: 'always' } },
    { level: 70, skill: { id: 'beast_king',        name: '伝説の獣王',       type: 'attack', description: '敵全体に3.2倍の攻撃＋パーティATK↑',               cooldownMs: 55000, mpCost: 60, autoCondition: 'always' } },
    { level: 99, skill: { id: 'god_summon',         name: '神獣召喚',         type: 'attack', description: '【奥義】神獣を召喚する。戦闘が終わるまで毎行動ごとに神獣が自動的に全敵を攻撃し続ける永続効果', cooldownMs: 90000, mpCost: 99, autoCondition: 'combat_start' } },
  ],
  enchanter: [
    { level:  1, skill: { id: 'magic_blade',       name: '魔剣',             type: 'attack',  description: '魔力を込めた剣で敵1体に1.5倍',                     cooldownMs:  3000, mpCost:  8, autoCondition: 'always' } },
    { level:  5, skill: { id: 'enchant',           name: '付与強化',         type: 'buff',    description: '自身のATK↑（最大3段）',                           cooldownMs:  8000, mpCost: 12, autoCondition: 'combat_start', buffEffects: ['atk_up'], buffTarget: 'self' } },
    { level: 10, skill: { id: 'aura_boost',        name: 'オーラ昇華',       type: 'buff',    description: '自身のATK↑・集中',                                 cooldownMs: 15000, mpCost: 15, autoCondition: 'always', buffEffects: ['atk_up', 'focus'], buffTarget: 'self' } },
    { level: 15, skill: { id: 'magic_barrier',     name: '魔法障壁',         type: 'buff',    description: '自身に結界付与',                                   cooldownMs: 20000, mpCost: 18, autoCondition: 'hp_below_50', buffEffects: ['barrier'], buffTarget: 'self' } },
    { level: 20, skill: { id: 'blade_dance',       name: '魔剣乱舞',         type: 'attack', description: '敵全体に1.8倍の魔法剣攻撃',                        cooldownMs: 30000, mpCost: 38, autoCondition: 'always' } },
    { level: 30, skill: { id: 'mass_enchant',      name: '全体付与',         type: 'buff',    description: 'パーティ全体のATK↑',                              cooldownMs: 30000, mpCost: 35, autoCondition: 'combat_start', buffEffects: ['atk_up'], buffTarget: 'party' } },
    { level: 40, skill: { id: 'mana_enhance',      name: '魔力強化',         type: 'buff',    description: '自身のATK↑↑・集中',                              cooldownMs: 22000, mpCost: 28, autoCondition: 'always', buffEffects: ['atk_up', 'focus'], buffTarget: 'self' } },
    { level: 55, skill: { id: 'blade_storm',       name: '剣の嵐',           type: 'attack', description: '敵全体に2.2倍×2回の魔法剣連撃',                    cooldownMs: 35000, mpCost: 45, autoCondition: 'always' } },
    { level: 70, skill: { id: 'blade_mastery',     name: '魔剣極意',         type: 'attack', description: '敵1体に4.0倍の魔剣必殺＋自身ATK↑↑',               cooldownMs: 45000, mpCost: 55, autoCondition: 'always' } },
    { level: 99, skill: { id: 'mana_conversion',   name: '魔力転換斬',       type: 'attack', description: '【奥義】残りMP全量を純粋な斬撃力に変換する。MP→0になる代わりに消費MPに比例した超斬撃が炸裂', cooldownMs: 90000, mpCost: 99, autoCondition: 'always' } },
  ],
}

export function getLearnedSkills(charClass: CharacterClass, level: number): SkillCard[] {
  return SKILL_MASTER[charClass]
    .filter((entry) => entry.level <= level)
    .map((entry) => ({ ...entry.skill, lastUsedAt: 0 }))
}
